version: '3.8'
services:
  web:
    build:
      context: .
      target: final
    ports:
      - 8080:8080

    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  db:
    image: postgres
    restart: always

    volumes:
       - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "ConcertDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mila"

    expose:
      - 5432

volumes:
  db-data:
