version: '3.8'
services:
  web:
    build:
      context: .
      target: final
    ports:
      - 8080:8080

# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  db:
    image: postgres
    restart: always
#     user: postgres
#     secrets:
#       - db-password
    volumes:
       - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "ConcertDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mila"
#       - POSTGRES_DBexample
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432

volumes:
  db-data:
# secrets:
#   db-password:
#     file: db/password.txt

